pull_request_rules:
  - name: automatic merge scala steward update on travis success
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - author=scala-steward
    actions:
      merge:
        method: squash
