language: scala

matrix:
  include:
  - jdk: oraclejdk8
    scala: 2.12.4
  - jdk: oraclejdk7
    scala: 2.10.7

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile scripted
